name: Android Artifact Build

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - release*
      - master
      - develop*

jobs:
  maven-publish:
    uses: mosip/kattu/.github/workflows/maven-publish-android.yml@master
    with:
      SERVICE_LOCATION: '.'
      ANDROID_SERVICE_LOCATION: 'android'
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_URL: ${{secrets.OSSRH_URL }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
#      Specify secrets.SLACK_WEBHOOK_URL (maven-publish/maven-android build) Error => Either Kattu has to be changed to SLACK_WEBHOOK_INJI_TEAM or this to SLACK_WEBHOOK_URL
#      gpg: can't open './.github/keys/mosipgpgkey_pub.gpg': No such file or directory => GPG Keys not present in the repository
